# Generated by Django 5.1.7 on 2025-04-01 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('available_slots', models.IntegerField(default=0)),
                ('participants', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Kolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zapasnik_a', models.CharField(max_length=100)),
                ('zapasnik_b', models.CharField(max_length=100)),
                ('uzavreno', models.BooleanField(default=False)),
                ('vitez', models.CharField(blank=True, choices=[('A', 'Zápasník A'), ('B', 'Zápasník B')], max_length=1, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kola', to='poradatel.event')),
            ],
        ),
    ]
