# Generated by Django 5.1.7 on 2025-04-01 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poradatel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='available_slots',
            new_name='max_slots',
        ),
    ]
