# Generated by Django 5.1.7 on 2025-04-01 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OverlayMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='Ahoj', max_length=255)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
